FIREFOX_DRIVER_PATH = r'D:\\downloads\\software\\geckodriver-v0.27.0-win64\\geckodriver.exe'

project_version = '0.5.6'

# the id of the auction i.e. the last parameter of the URL
# https://scrap.tf/auctions/auction_id
# it appears that the id is always a 6 digit combo of upper case letters and numbers
auction_id = ''

# there are some inconsistencies in how some strange parts are named on scrap.tf site and bp.tf, therefore the
#  conversion is necessary
strange_part_inconsistencies = {
    "Airborne Enemy Kills": "Airborne Enemies Killed"
}
# on scrap.tf unusual effects are displayed as their names while on bp.tf the classifieds search query uses
#  the following id's
# as a result, a conversion dict had to be made, in order to translate the name into the id.
particles_dict = {
    "'72": 3004,
    "Abduction": 91,
    "Abyssal Aura": 125,
    "Accursed": 3024,
    "Aces High": 59,
    "Acidic Bubbles of Envy": 3017,
    "Amaranthine": 82,
    "Arcane Assistance": 3039,
    "Arcana": 73,
    "Arachnid Assault": 3047,
    "Anti-Freeze": 69,
    "Ancient Eldritch": 105,
    "Ancient Codex": 98,
    "Aromatica": 148,
    "Arctic Aurora": 3033,
    "Astral Presence": 3038,
    "Atomic": 92,
    "Bee Swarm": 151,
    "Cauldron Bubbles": 39,
    "Burning Flames": 13,
    "Bewitched": 3023,
    "Bubbling": 34,
    "Brain Drain": 111,
    "Bonzo The All-Gnawing": 81,
    "Blizzardy Storm": 30,
    "Chiroptera Venenata": 75,
    "Cloud 9": 58,
    "Cloudy Moon": 38,
    "Chromatica": 149,
    "Community Sparkle": 4,
    "Circling Heart": 19,
    "Cool": 703,
    "Creepy Crawlies": 3048,
    "Circling Peace Sign": 18,
    "Circling TF Logo": 11,
    "Darkblaze": 79,
    "Dead Presidents": 60,
    "Disco Beat Down": 62,
    "Clairvoyance": 121,
    "Eerie Lightning": 3027,
    "Emerald Allurement": 3041,
    "Electrostatic": 67,
    "Demonflame": 80,
    "Defragmenting Reality": 139,
    "Electric Hat Protector": 94,
    "Eldritch Flame": 106,
    "Death by Disco": 100,
    "Death at Dusk": 90,
    "Eerie Orbiting Fire": 40,
    "Enchanted": 3025,
    "Energy Orb": 704,
    "Ether Trail": 103,
    "Ethereal Essence": 129,
    "Festive Spirit": 3035,
    "Fifth Dimension": 122,
    "Fragmented Gluons": 136,
    "Fountain of Delight": 3005,
    "Flammable Bubbles of Attraction": 3018,
    "Flaming Lantern": 37,
    "Fragmented Photons": 138,
    "Fragmented Quarks": 137,
    "Fragmenting Reality": 141,
    "Frisky Fireflies": 152,
    "Frostbite": 87,
    "Ghastly Ghosts Jr": 85,
    "Ghastly Ghosts": 3012,
    "Genteel Smoke": 28,
    "Galactic Gateway": 114,
    "Galactic Codex": 97,
    "Frozen Icefall": 135,
    "Ghastly Grove": 127,
    "Good-Hearted Goodies": 3031,
    "Gourdian Angel": 162,
    "Gravelly Ghoul": 160,
    "Green Black Hole": 71,
    "Haunted Phantasm": 3011,
    "Haunted Ghosts": 8,
    "Green Giggler": 156,
    "Green Energy": 9,
    "Green Confetti": 6,
    "Haunted Phantasm Jr": 86,
    "Head of Steam": 113,
    "Hellfire": 78,
    "Hellish Inferno": 3013,
    "Harvest Moon": 45,
    "Holy Grail": 3003,
    "Hot": 701,
    "Infernal Flames": 3015,
    "It's a puzzle to me": 102,
    "It's a mystery to everyone": 101,
    "It's A Secret To Everybody": 46,
    "Isotope": 702,
    "Infernal Smoke": 3016,
    "Jarate Shock": 3029,
    "Kaleidoscope": 155,
    "Kill-a-Watt": 56,
    "Knifestorm": 43,
    "Laugh-O-Lantern": 157,
    "Magical Spirit": 3036,
    "Miami Nights": 61,
    "Menacing Miasma": 124,
    "Memory Leak": 65,
    "Mega Strike": 3010,
    "Massed Flies": 12,
    "Magnetic Hat Protector": 95,
    "Midnight Whirlwind": 3008,
    "Misty Skull": 44,
    "Molten Mallard": 88,
    "Morning Glory": 89,
    "Mystical Medley": 128,
    "Nebula": 99,
    "Open Mind": 112,
    "Omniscient Orb": 120,
    "Ominous Night": 3022,
    "Nuts n' Bolts": 31,
    "Neutron Star": 107,
    "Nether Void": 3030,
    "Nether Trail": 104,
    "Orbiting Fire": 33,
    "Overclocked": 66,
    "Phosphorous": 63,
    "Plum Prankster": 158,
    "Orbiting Planets": 32,
    "Poisoned Shadows": 76,
    "Purple Energy": 10,
    "Ring of Fire": 117,
    "Showstopper": 3001,
    "Snowfallen": 143,
    "Spellbound": 74,
    "Starstorm Slumber": 110,
    "Sulphurous": 64,
    "The Eldritch Opening": 115,
    "Verdant Vortex": 132,
    "Vivid Plasma": 16,
    "Wintery Wisp": 3032,
    "Winter Spirit": 3034,
    "Wicked Wood": 126,
    "Violet Vortex": 131,
    "Valiant Vortex": 133,
    "Veno Shock": 3045,
    "The Dark Doorway": 116,
    "Stormy Storm": 29,
    "Subatomic": 93,
    "Starstorm Insomnia": 109,
    "Spectral Escort": 3037,
    "Spectral Swirl": 3014,
    "Smoldering Spirits": 153,
    "Screaming Tiger": 3006,
    "Snowblinded": 144,
    "Refragmenting Reality": 142,
    "Purple Confetti": 7,
    "Searing Plasma": 15,
    "Pumpkin Party": 163,
    "Prismatica": 150,
    "Pyroland Nightmare": 159,
    "Pyrophoric Personality": 3042,
    "Power Surge": 68,
    "Poisonous Bubbles of Regret": 3019,
    "Pyroland Daydream": 145,
    "Roaring Rockets": 3020,
    "Roboactive": 72,
    "Scorching Flames": 14,
    "Smoking": 35,
    "Something Burning This Way Comes": 77,
    "Silver Cyclone": 3009,
    "Skill Gotten Gains": 3007,
    "Sparkling Lights": 134,
    "Stare From Beyond": 83,
    "Spooky Night": 3021,
    "Spellbound Aspect": 3043,
    "Static Mist": 3026,
    "Sunbeams": 17,
    "The Ooze": 84,
    "Verdatica": 147,
    "Voltaic Hat Protector": 96,
    "Wandering Wisps": 154,
    "Vexed Volcanics": 161,
    "Time Warp": 70,
    "Terrifying Thunder": 3028,
    "Steaming": 36,
    "Terror-Watt": 57,
    "Tesla Coil": 108,
    "Stormy 13th Hour": 47,
    "Static Shock": 3044,
    "Toxic Terrors": 3046,
    "Vicious Circle": 118,
    "Vicious Vortex": 123,
    "Twisted Radiance": 130,
    "White Lightning": 119,
}

